# Generated by Django 5.0 on 2023-12-07 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suiveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suiveurs', to=settings.AUTH_USER_MODEL)),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('suiveur', 'suivi')},
            },
        ),
    ]
