# Generated by Django 4.2.7 on 2023-12-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_suivi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
